/**
 * Created by Kiran on 09/22/2015.
 */
EndpointTabs.factory('dataStore', [
    function() {
        var dataStore = {
            endpointUrl : "https://api-pilot.ubx.ibmmarketingcloud.com/v1/endpoint",
            endpointAuthorization : "Bearer 90cced80-1920-4e67-80c8-86168313f1c9",
            endpointContentType : "application/JSON; charset=utf-8",
            sourceEndpointPayload : "{\n\n    \"name\":\"EmailMarketingSource\",\n    \"description\":\"EmailMarketingSource\",\n    \"providerName\":\"IBM\",\n  \"url\":\"http://169.45.67.107:5555/timedevent\",\n    \"endpointTypes\":{\n        \"event\":{\n            \"source\":{\n                \"enabled\":true\n            },\n            \"destination\":{\n                \"enabled\":false,\n                \"url\":\"http://169.45.67.107:5555/timedevent\",\n                \"destinationType\":\"push\"\n            }\n        }\n    },\n    \"marketingDatabasesDefinition\":{\n        \"marketingDatabases\":[\n            {\n                \"name\":\"marketingDB--name-QA1-000\",\n                \"identifiers\":[\n                    {\n                        \"name\":\"marketingDB--identifiers--name-QA1-000\",\n                        \"type\":\"marketingDB--identifiers--type-QA1-000\"\n                    }\n                ],\n                \"attributes\":[\n                    {\n                        \"name\":\"marketingDB--attributes--name-QA1-000\",\n                        \"type\":\"marketingDB--attributes--type-QA1-000\",\n                        \"isRequired\":false\n                    }\n                ]\n            }\n        ]\n    }\n\n} ",
            destinationEndpointPayload : "{\n\n    \"name\":\"GenericDestination\",\n    \"description\":\"GenericDestination\",\n    \"providerName\":\"IBM\",\n  \"url\":\"http://169.45.67.107:5555/timedevent\",\n    \"endpointTypes\":{\n        \"event\":{\n            \"source\":{\n                \"enabled\":false\n            },\n            \"destination\":{\n                \"enabled\":true,\n                \"url\":\"http://169.45.67.107:5555/timedevent\",\n                \"destinationType\":\"push\"\n            }\n        }\n    },\n    \"marketingDatabasesDefinition\":{\n        \"marketingDatabases\":[\n            {\n                \"name\":\"marketingDB--name-QA1-000\",\n                \"identifiers\":[\n                    {\n                        \"name\":\"marketingDB--identifiers--name-QA1-000\",\n                        \"type\":\"marketingDB--identifiers--type-QA1-000\"\n                    }\n                ],\n                \"attributes\":[\n                    {\n                        \"name\":\"marketingDB--attributes--name-QA1-000\",\n                        \"type\":\"marketingDB--attributes--type-QA1-000\",\n                        \"isRequired\":false\n                    }\n                ]\n            }\n        ]\n    }\n\n} ",
            sourceAudienceEndpointPayload : "{  \r\n   \"name\":\"EmailMarketingSourceAudience\",\r\n   \"description\":\"UBX Demo producer Endpoint\",\r\n   \"providerName\":\"IBM\",\r\n   \"url\":\"http:\/\/169.45.67.107:8096\/SegmentEndpoint\",\r\n   \"endpointTypes\":{  \r\n      \"segment\":{  \r\n         \"source\":{  \r\n            \"enabled\":true\r\n         }\r\n      }\r\n   },\r\n   \"marketingDatabasesDefinition\":{  \r\n      \"marketingDatabases\":[  \r\n         {  \r\n            \"name\":\"marketingDBSource1\",\r\n            \"identifiers\" : [              \r\n\t\t\t\t\t{ \"name\" : \"Email\",          \r\n\t\t\t\t\t\"type\" : \"email\"      \r\n\t\t\t\t\t}\r\n\t\t\t],\r\n            \"attributes\":[  \r\n\t\t\t\t\t{ \"name\" : \"FirstName\",          \r\n\t\t\t\t\t\"type\" : \"string\"      \r\n\t\t\t\t\t},\r\n\t\t\t\t\t{ \"name\" : \"LastName\",          \r\n\t\t\t\t\t\"type\" : \"string\"      \r\n\t\t\t\t\t},\r\n\t\t\t\t\t{ \"name\" : \"Sex\",          \r\n\t\t\t\t\t\"type\" : \"string\"      \r\n\t\t\t\t\t}\r\n            ]\r\n         }\r\n      ]\r\n   }\r\n} ",
            destinationAudienceEndpointPayload : "{  \r\n   \"name\":\"EmailMarketingDestinationAudience\",\r\n   \"description\":\"UBX Demo consumer Endpoint\",\r\n   \"providerName\":\"IBM\",\r\n   \"url\":\"http:\/\/169.45.67.107:8096\/SegmentEndpoint\",\r\n   \"endpointTypes\":{  \r\n      \"segment\":{  \r\n         \"destination\":{  \r\n            \"enabled\":true,\r\n            \"destinationType\":\"push\"\r\n         }\r\n      }\r\n   },\r\n   \"marketingDatabasesDefinition\":{  \r\n      \"marketingDatabases\":[  \r\n         {  \r\n            \"name\":\"marketingDBSource1\",\r\n            \"identifiers\" : [              \r\n\t\t\t\t\t{ \r\n\t\t\t\t\t\t\"name\":\"EMAIL_SHA256\",\r\n\t\t\t\t\t\t\"type\":\"email\",\r\n\t\t\t\t\t\t\"hashAlgorithm\":\"EMAIL_SHA256\",\r\n\t\t\t\t\t\t\"hashMode\":\"HASHED\"\r\n\t\t\t\t\t}\r\n\t\t\t],\r\n            \"attributes\":[  \r\n\t\t\t\t\t{ \"name\" : \"FName\",          \r\n\t\t\t\t\t\"type\" : \"string\"      \r\n\t\t\t\t\t},\r\n\t\t\t\t\t{ \"name\" : \"LName\",          \r\n\t\t\t\t\t\"type\" : \"string\"      \r\n\t\t\t\t\t},\r\n\t\t\t\t\t{ \"name\" : \"Gender\",          \r\n\t\t\t\t\t\"type\" : \"string\"      \r\n\t\t\t\t\t}\r\n            ]\r\n         }\r\n      ]\r\n   }\r\n} ",
            sampleEventPayload : "{\r\n\r\n  \"channel\" : \"Email\",\r\n\r\n  \"identifiers\" : [ {\r\n\r\n    \"name\" : \"contactId\",\r\n\r\n    \"value\" : \"4\"\r\n\r\n  }, {\r\n\r\n    \"name\" : \"email\",\r\n\r\n    \"value\" : \"teamparam@us.ibm.com\"\r\n\r\n  } ],\r\n\r\n  \"events\" : [ {\r\n\r\n    \"code\" : \"emailSend\",\r\n\r\n    \"timestamp\" : \"2010-07-29T13:33:59.028Z\",\r\n\r\n    \"attributes\" : [ {\r\n\r\n      \"name\" : \"eventId\",\r\n\r\n      \"value\" : null,\r\n\r\n      \"type\" : \"string\"\r\n\r\n    }, {\r\n\r\n      \"name\" : \"eventName\",\r\n\r\n      \"value\" : \"Mailing Open Event\",\r\n\r\n      \"type\" : \"string\"\r\n\r\n    }, {\r\n\r\n      \"name\" : \"description\",\r\n\r\n      \"value\" : \"Mailing Open Event\",\r\n\r\n      \"type\" : \"string\"\r\n\r\n    }, {\r\n\r\n      \"name\" : \"messageId\",\r\n\r\n      \"value\" : \"11835\",\r\n\r\n      \"type\" : \"number\"\r\n\r\n    }, {\r\n\r\n      \"name\" : \"mailingTemplateId\",\r\n\r\n      \"value\" : \"42\",\r\n\r\n      \"type\" : \"number\"\r\n\r\n    }, {\r\n\r\n      \"name\" : \"reportId\",\r\n\r\n      \"value\" : \"2\",\r\n\r\n      \"type\" : \"number\"\r\n\r\n    }, {\r\n\r\n      \"name\" : \"subjectLine\",\r\n\r\n      \"value\" : \"FitNesse Test Mailing Behaviors\",\r\n\r\n      \"type\" : \"string\"\r\n\r\n    }, {\r\n\r\n      \"name\" : \"messageName\",\r\n\r\n      \"value\" : \"Fit Email Behavior Test Mailing_4127496407341\",\r\n\r\n      \"type\" : \"string\"\r\n\r\n    }, {\r\n\r\n      \"name\" : \"docType\",\r\n\r\n      \"value\" : \"html\",\r\n\r\n      \"type\" : \"string\"\r\n\r\n    } ]\r\n\r\n  } ]\r\n\r\n}",
            eventUrl : "https://api-pilot.ubx.ibmmarketingcloud.com/v1/event",
            eventTypeUrl : "https://api-pilot.ubx.ibmmarketingcloud.com/v1/eventtype",
            eventTypePayload : "{\r\n    \"code\":\"emailSend\",\r\n    \"name\":\"emailSend\",\r\n    \"description\":\"Email send event\",\r\n    \"version\" : 1,\r\n    \"namespace\" : \"com.acme.pilot\",\r\n\r\n \"attributes\" : [ {\r\n      \"name\" : \"eventName\",\r\n      \"type\" : \"string\"\r\n    }, {\r\n      \"name\" : \"messageId\",\r\n      \"type\" : \"string\"\r\n    }, {\r\n      \"name\" : \"subjectLine\",\r\n      \"type\" : \"string\"\r\n    }]\r\n} ",
            getSegmentsUrlModel : "http://169.45.67.107:8096/SegmentEndpoint/v1/segments"
        };
        return dataStore;
    }]);