/**
 * Created by Kiran on 09/22/2015.
 */
EndpointTabs.factory('dataStore', [
    function() {
        var dataStore = {
            endpointUrl : "https://api-pilot.ubx.ibmmarketingcloud.com/v1/endpoint",
            endpointAuthorization : "Bearer 90cced80-1920-4e67-80c8-86168313f1c9",
            endpointContentType : "application/JSON; charset=utf-8",
            sourceEndpointPayload : "{\n\n    \"name\":\"SourceEndpoint\",\n    \"description\":\"SourceEndpoint\",\n    \"providerName\":\"IBM\",\n  \"url\":\"http://169.45.67.107:5555/timedevent\",\n    \"endpointTypes\":{\n        \"event\":{\n            \"source\":{\n                \"enabled\":true\n            },\n            \"destination\":{\n                \"enabled\":false,\n                \"url\":\"http://169.45.67.107:5555/timedevent\",\n                \"destinationType\":\"push\"\n            }\n        }\n    },\n    \"marketingDatabasesDefinition\":{\n        \"marketingDatabases\":[\n            {\n                \"name\":\"marketingDB--name-QA1-000\",\n                \"identifiers\":[\n                    {\n                        \"name\":\"marketingDB--identifiers--name-QA1-000\",\n                        \"type\":\"marketingDB--identifiers--type-QA1-000\"\n                    }\n                ],\n                \"attributes\":[\n                    {\n                        \"name\":\"marketingDB--attributes--name-QA1-000\",\n                        \"type\":\"marketingDB--attributes--type-QA1-000\",\n                        \"isRequired\":false\n                    }\n                ]\n            }\n        ]\n    }\n\n} ",
            destinationEndpointPayload : "{\n\n    \"name\":\"DestinationEndpoint\",\n    \"description\":\"DestinationEndpoint\",\n    \"providerName\":\"IBM\",\n  \"url\":\"http://169.45.67.107:5555/timedevent\",\n    \"endpointTypes\":{\n        \"event\":{\n            \"source\":{\n                \"enabled\":false\n            },\n            \"destination\":{\n                \"enabled\":true,\n                \"url\":\"http://169.45.67.107:5555/timedevent\",\n                \"destinationType\":\"push\"\n            }\n        }\n    },\n    \"marketingDatabasesDefinition\":{\n        \"marketingDatabases\":[\n            {\n                \"name\":\"marketingDB--name-QA1-000\",\n                \"identifiers\":[\n                    {\n                        \"name\":\"marketingDB--identifiers--name-QA1-000\",\n                        \"type\":\"marketingDB--identifiers--type-QA1-000\"\n                    }\n                ],\n                \"attributes\":[\n                    {\n                        \"name\":\"marketingDB--attributes--name-QA1-000\",\n                        \"type\":\"marketingDB--attributes--type-QA1-000\",\n                        \"isRequired\":false\n                    }\n                ]\n            }\n        ]\n    }\n\n} ",
            sampleEventPayload : "{\r\n\r\n    \"provider\":\"IBM\",\r\n    \"channel\":\"Natural Search Activity\",\r\n    \"identifiers\":[\r\n        {\r\n            \"name\":\"Email\",\r\n            \"value\":\"ibmtest@ibm.com\"\r\n        },\r\n        {\r\n            \"name\":\"Cookie\",\r\n            \"value\":\"35139876006927234532803\"\r\n        }\r\n    ],\r\n    \"events\":[\r\n        {\r\n            \"code\" : \"eventcode\",\r\n            \"timestamp\":\"2015-07-29T09:36:53-0400\",\r\n            \"attributes\":[\r\n                {\r\n                    \"name\":\"Email\",\r\n                    \"value\":\"ibm@ibm.com\",\r\n                    \"type\":\"string\"\r\n                },\r\n                {\r\n                    \"name\":\"MobileId\",\r\n                    \"value\":\"12345\",\r\n                    \"type\":\"numeric\"\r\n                }\r\n            ]\r\n        }\r\n    ]\r\n\r\n} \r\n",
            eventUrl : "https://api-pilot.ubx.ibmmarketingcloud.com/v1/event",
            eventTypeUrl : "https://api-pilot.ubx.ibmmarketingcloud.com/v1/eventtype",
            eventTypePayload : "{\r\n    \"code\":\"eventcode\",\r\n    \"name\":\"MarketingEvent\",\r\n    \"description\":\"MarketingEvent\"\r\n} "
        };
        return dataStore;
    }]);