/**
 * Created by Kiran on 09/22/2015.
 */
EndpointTabs.factory('dataStore', [
    function() {
        var dataStore = {
            endpointUrl : "https://api-pilot.ubx.ibmmarketingcloud.com/v1/endpoint",
            endpointAuthorization : "Bearer 90cced80-1920-4e67-80c8-86168313f1c9",
            endpointContentType : "application/JSON; charset=utf-8",
            sourceEndpointPayload : "{\n\n    \"name\":\"KGSourceEndpoint\",\n    \"description\":\"KGSourceEndpoint\",\n    \"providerName\":\"IBM\",\n  \"url\":\"http://169.45.67.107:5555/timedevent\",\n    \"endpointTypes\":{\n        \"event\":{\n            \"source\":{\n                \"enabled\":true\n            },\n            \"destination\":{\n                \"enabled\":false,\n                \"url\":\"http://169.45.67.107:5555/timedevent\",\n                \"destinationType\":\"push\"\n            }\n        }\n    },\n    \"marketingDatabasesDefinition\":{\n        \"marketingDatabases\":[\n            {\n                \"name\":\"marketingDB--name-QA1-000\",\n                \"identifiers\":[\n                    {\n                        \"name\":\"marketingDB--identifiers--name-QA1-000\",\n                        \"type\":\"marketingDB--identifiers--type-QA1-000\"\n                    }\n                ],\n                \"attributes\":[\n                    {\n                        \"name\":\"marketingDB--attributes--name-QA1-000\",\n                        \"type\":\"marketingDB--attributes--type-QA1-000\",\n                        \"isRequired\":false\n                    }\n                ]\n            }\n        ]\n    }\n\n} ",
            destinationEndpointPayload : "{\n\n    \"name\":\"KGDestinationEndpoint\",\n    \"description\":\"KGDestinationEndpoint\",\n    \"providerName\":\"IBM\",\n  \"url\":\"http://169.45.67.107:5555/timedevent\",\n    \"endpointTypes\":{\n        \"event\":{\n            \"source\":{\n                \"enabled\":false\n            },\n            \"destination\":{\n                \"enabled\":true,\n                \"url\":\"http://169.45.67.107:5555/timedevent\",\n                \"destinationType\":\"push\"\n            }\n        }\n    },\n    \"marketingDatabasesDefinition\":{\n        \"marketingDatabases\":[\n            {\n                \"name\":\"marketingDB--name-QA1-000\",\n                \"identifiers\":[\n                    {\n                        \"name\":\"marketingDB--identifiers--name-QA1-000\",\n                        \"type\":\"marketingDB--identifiers--type-QA1-000\"\n                    }\n                ],\n                \"attributes\":[\n                    {\n                        \"name\":\"marketingDB--attributes--name-QA1-000\",\n                        \"type\":\"marketingDB--attributes--type-QA1-000\",\n                        \"isRequired\":false\n                    }\n                ]\n            }\n        ]\n    }\n\n} "
        };
        return dataStore;
    }]);